#! /bin/sh

case "$1" in
        start)
		echo "SPI modules loading"
		modprobe spidev
		modprobe spi-bcm2835
		;;

        stop)
		echo "SPI modules unloading"
                rmmod spi-bcm2835
		rmmod spidev
                ;;
        *)
                echo "Usage : $0 {start|stop}"
        exit 1
esac
